import type { Metadata } from 'next'
import { Big_Shoulders_Display, Lexend_Deca } from 'next/font/google'
import './globals.css'

const lexendDeca = Lexend_Deca({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-lexend-deca'
})
const bigShouldersDisplay = Big_Shoulders_Display({
  subsets: ['latin'],
  weight: '700',
  variable: '--font-big-shoulders-display'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${lexendDeca.variable} ${bigShouldersDisplay.variable}`}>
      <body className={`font-body`}>{children}</body>
    </html>
  )
}
